name: The EARs Reviewing bot for PRs

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]
    paths:
      - "**.pdf"

jobs:
  add-label-and-supervisor:
    runs-on: ubuntu-latest
    env:
      SUPERVISOR: brilliantarash
    steps:
      - name: Add label
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["ERGA-BGE"]
            });

      - name: Add Supervisor
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: ["${{ env.SUPERVISOR }}"]
            });

            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers: ["${{ env.SUPERVISOR }}"]
            });

      - name: Create comment for supervisor
        uses: actions/github-script@v7
        with:
          script: |
            const researcher = context.payload.pull_request.user.login;
            const message1 = `ðŸ‘‹ Hi @${researcher}, thanks for sending the EAR.\nI added the corresponding tag to the PR and appointed @${{ env.SUPERVISOR }} as the assignee to supervise.`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message1
            });
