name: The EARs Reviewing bot for assigning reviewer

on:
  workflow_run:
    workflows: [The EARs Reviewing bot]
    types:
      - completed

jobs:
  add-reviewer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ear_bot/requirements.txt

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: artifact.json

      - name: Run python script to assign reviewer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          REVIEWER: arash77,brilliantarash
          ARTIFACT_PATH: artifact.json
        run: python -u ear_bot/ear_bot_reviewer.py

      - name: Uplaod Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: artifact.json
